import i18n from './i18n'

const en = {
    back: 'Back',
    language: 'Language',
    accessibility: 'Accessibility',
    colors: 'Colors',
    close: 'Close',
    decrypt: 'Decrypt invitation',
    decrypting: 'Decrypting…',
    enable: 'Enable phone tilt',
    disable: 'Disable phone tilt',
    reduced: 'Reduce motion',
    contrast: 'High contrast',
    accessIntro:
        'The sand moves automatically. Phone tilt is optional. Reduce motion stops both.',
    off: 'Ambient animation is on. Phone tilt is off.',
    requesting: 'Waiting for permission',
    waiting: 'Waiting for phone movement',
    on: 'Phone tilt is on',
    denied: 'Phone tilt permission declined. The invitation still works.',
    unavailable: 'Phone tilt is unavailable in this browser',
    paused: 'Motion is reduced',
    paletteIntro: 'Your hologram your colors',
    reset: 'Reset colors',
    paletteNote:
        'Colors stay saved on this device. High contrast temporarily overrides them.',
    background: 'Background',
    surface: 'Panel surface',
    text: 'Main text',
    muted: 'Secondary text',
    title: 'Title',
    accent: 'Primary light',
    dust: 'Falling sand',
    rim: 'Bright particles',
    glow: 'Glow',
    line: 'Borders',
    button: 'Button color',
    buttonText: 'Button text',
    level: 'Level number',
    calendar: 'Add to calendar',
    calendarTitle: 'Save progress',
    calendarPending: 'Calendar details are not ready yet',
    share: 'Share the quest',
    shareTitle: 'Share the quest',
    shareNote: 'Open invite friends welcome',
    backup: 'Backup share link',
    qrPending: 'QR coming soon',
    copy: 'Copy link',
    copied: 'Link copied',
    copyFailed: 'Select and copy the link',
    details: 'Quest details',
    photos: 'Backpack',
    photosTitle: 'Backpack',
    public: 'PUBLIC',
    publicNote:
        'This folder is PUBLIC. I am not responsible for the life mistakes you upload',
    drive: 'Open photo folder',
    hobby:
        'A hobby. Gaming is my chosen time burner, so streaming gives me an excuse to learn sound and video engineering with an excuse to make art.',

    game: {
        title: 'SEAN VS. EXISTENCE',
        stats: 'Player stats',
        level: 'LVL',
        health: 'HEALTH',
        healthValue: 'STILL HERE',
        kd: 'KILL/DEATH RATIO',
        days: 'DAYS SURVIVED',
        quest: 'QUEST',
        questCopy: "Arrive, or don't, I can't tell you what to do",
        when: 'WHEN',
        arrival: 'Show up whenever, I’m planning to stay until 1 AM.',
        map: 'MAP LOCATION',
        save: 'SAVE PROGRESS?',
        rsvp: 'No RSVP needed!',
        equipment: 'EQUIPMENT',
        equipmentCopy: 'ID',
        food: 'FOOD',
        foodCopy: 'Not a dinner thing',
        find: 'SUB-OBJECTIVE: FIND SEAN',
        findCopy:
            'Can’t find me? Probably outside smoking weed searching for caffeine',
        consumables: 'CONSUMABLES',
        consumablesCopy:
            "Cannabis guy. I might have a drink or two so don't buy me alcohol so I have to awkwardly turn it down",
        gifts: 'GIFTS',
        giftsCopy: 'NO GIFTS.',
        side: 'SIDE OBJECTIVES',
        driveSafe: 'DO NOT DRINK AND DRIVE',
        babies: 'NO ACCIDENTAL BABIES',
        backpack: 'BACKPACK',
        photoLink: 'Open the PUBLIC photo folder',
        publicBefore: 'This folder is ',
        publicWord: 'PUBLIC',
        publicAfter:
            '. I am not responsible for the life mistakes you upload',
        friends: 'FRIEND LIST',
        instagram: 'Sean’s Instagram',
        twitch: 'Sean’s Twitch',
        hobby:
            'A hobby. Gaming is my chosen time burner, so streaming gives me an excuse to learn sound and video engineering with an excuse to make art.',
        faq: 'FAQ so I dont have to talk in loops',
        workQ: 'What do you do?',
        workA: 'Experimental Coding with the Classic LA side hustle',
        fromQ: 'Where are you from?',
        fromA: 'San Bernardino',
        backgroundQ: 'Whats your background?',
        backgroundA:
            'PreK education working with students with moderate to severe disabilities',
        educationQ: 'Why no longer in ed?',
        educationA:
            'I emotionally burnt out, I was with CPS easily 3–4 times a month. I decided if I am going to have functioning relationships I cannot come home righteously enraged with the system and burned out',
        weedQ: 'What your favorite weed?',
        weedA: 'Hybrid',
        funQ: 'What do you do for fun?',
        funA:
            'Art, building and actually finishing ludicrous projects that serve 0 commercial purpose, gardening, programming…',
        share: 'SHARE THE QUEST',
        qrPending: 'QR coming soon',
        qrExplanation: 'The website link goes here once it is deployed',
        backup: 'Backup Share Link',
        links: 'Friend list',
        more: 'Quest details',
        calendar: 'Add to calendar',
        notWorking: 'Not working?',
        calendarPending: 'Backup calendar link / QR coming soon',
        actions: 'Quest actions',
        cancelled: 'EVENT CANCELLED',
    },
}

const es = {
    back: 'Volver',
    language: 'Idioma',
    accessibility: 'Accesibilidad',
    colors: 'Colores',
    close: 'Cerrar',
    decrypt: 'Descifrar invitación',
    decrypting: 'Descifrando…',
    enable: 'Activar inclinación del teléfono',
    disable: 'Desactivar inclinación del teléfono',
    reduced: 'Reducir movimiento',
    contrast: 'Alto contraste',
    accessIntro:
        'La arena se mueve automáticamente. La inclinación es opcional. Reducir movimiento detiene ambos efectos.',
    off: 'La animación ambiental está activa. La inclinación está desactivada.',
    requesting: 'Esperando permiso',
    waiting: 'Esperando movimiento del teléfono',
    on: 'Inclinación activada',
    denied:
        'Se rechazó el permiso de inclinación. La invitación sigue funcionando.',
    unavailable: 'La inclinación no está disponible en este navegador',
    paused: 'Movimiento reducido',
    paletteIntro: 'Tu holograma tus colores',
    reset: 'Restablecer colores',
    paletteNote:
        'Los colores se guardan en este dispositivo. El alto contraste los sustituye temporalmente.',
    background: 'Fondo',
    surface: 'Superficie del panel',
    text: 'Texto principal',
    muted: 'Texto secundario',
    title: 'Título',
    accent: 'Luz principal',
    dust: 'Arena que cae',
    rim: 'Partículas brillantes',
    glow: 'Resplandor',
    line: 'Bordes',
    button: 'Color del botón',
    buttonText: 'Texto del botón',
    level: 'Número de nivel',
    calendar: 'Añadir al calendario',
    calendarTitle: 'Guardar partida',
    calendarPending: 'Los datos del calendario todavía no están listos',
    share: 'Compartir la misión',
    shareTitle: 'Compartir la misión',
    shareNote: 'Invitación abierta tus amigos son bienvenidos',
    backup: 'Enlace alternativo para compartir',
    qrPending: 'QR próximamente',
    copy: 'Copiar enlace',
    copied: 'Enlace copiado',
    copyFailed: 'Selecciona y copia el enlace',
    details: 'Detalles de la misión',
    photos: 'Mochila',
    photosTitle: 'Mochila',
    public: 'PÚBLICA',
    publicNote:
        'Esta carpeta es PÚBLICA. No me hago responsable de los errores de vida que subas',
    drive: 'Abrir carpeta de fotos',
    hobby:
        'Un pasatiempo. Los videojuegos son mi forma favorita de gastar tiempo, así que transmitir me da una excusa para aprender ingeniería de sonido y video y hacer arte.',

    game: {
        title: 'SEAN VS. LA EXISTENCIA',
        stats: 'Estadísticas del jugador',
        level: 'NIVEL',
        health: 'SALUD',
        healthValue: 'SIGUE AQUÍ',
        kd: 'BAJAS/MUERTES',
        days: 'DÍAS SOBREVIVIDOS',
        quest: 'MISIÓN',
        questCopy: 'Ven, o no, no puedo decirte qué hacer',
        when: 'CUÁNDO',
        arrival: 'Llega cuando quieras, pienso quedarme hasta la 1 AM.',
        map: 'UBICACIÓN EN EL MAPA',
        save: '¿GUARDAR PARTIDA?',
        rsvp: '¡No necesitas confirmar asistencia!',
        equipment: 'EQUIPO',
        equipmentCopy: 'Identificación',
        food: 'COMIDA',
        foodCopy: 'No es una cena',
        find: 'MISIÓN SECUNDARIA: ENCONTRAR A SEAN',
        findCopy:
            '¿No me encuentras? Probablemente esté afuera fumando marihuana y buscando cafeína',
        consumables: 'CONSUMIBLES',
        consumablesCopy:
            'Prefiero el cannabis. Quizá tome una o dos copas así que no me compres alcohol para que tenga que rechazarlo incómodamente',
        gifts: 'REGALOS',
        giftsCopy: 'SIN REGALOS.',
        side: 'OBJETIVOS SECUNDARIOS',
        driveSafe: 'NO MANEJES SI TOMASTE',
        babies: 'NADA DE BEBÉS POR ACCIDENTE',
        backpack: 'MOCHILA',
        photoLink: 'Abrir la carpeta PÚBLICA de fotos',
        publicBefore: 'Esta carpeta es ',
        publicWord: 'PÚBLICA',
        publicAfter:
            '. No me hago responsable de los errores de vida que subas',
        friends: 'LISTA DE AMIGOS',
        instagram: 'Instagram de Sean',
        twitch: 'Twitch de Sean',
        hobby:
            'Un pasatiempo. Los videojuegos son mi forma favorita de gastar tiempo, así que transmitir me da una excusa para aprender ingeniería de sonido y video y hacer arte.',
        faq: 'Preguntas frecuentes para no repetir lo mismo',
        workQ: '¿A qué te dedicas?',
        workA:
            'Programación experimental con el clásico trabajo extra de Los Ángeles',
        fromQ: '¿De dónde eres?',
        fromA: 'San Bernardino',
        backgroundQ: '¿Cuál es tu experiencia?',
        backgroundA:
            'Educación preescolar con estudiantes con discapacidades de moderadas a severas',
        educationQ: '¿Por qué dejaste la educación?',
        educationA:
            'Terminé emocionalmente agotado, tenía contacto con los servicios de protección infantil fácilmente 3–4 veces al mes. Decidí que si quiero tener relaciones que funcionen no puedo llegar a casa agotado y lleno de indignación con el sistema',
        weedQ: '¿Qué tipo de marihuana prefieres?',
        weedA: 'Híbrida',
        funQ: '¿Qué haces para divertirte?',
        funA:
            'Arte, construir y de verdad terminar proyectos ridículos sin ningún fin comercial, jardinería, programación…',
        share: 'COMPARTIR LA MISIÓN',
        qrPending: 'QR próximamente',
        qrExplanation: 'Aquí irá el enlace cuando se publique el sitio',
        backup: 'Enlace alternativo para compartir',
        links: 'Lista de amigos',
        more: 'Detalles de la misión',
        calendar: 'Añadir al calendario',
        notWorking: '¿No funciona?',
        calendarPending: 'Enlace / QR alternativo de calendario próximamente',
        actions: 'Acciones de la misión',
        cancelled: 'EVENTO CANCELADO',
    },
}

i18n.addResourceBundle('en', 'translation', en, true, true)
i18n.addResourceBundle('es', 'translation', es, true, true)